<?php

use Illuminate\Database\Seeder;

class ReviewTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reviews')->insert([
            [
                'user_id' => '30',
                'country_id' => '1',
                'recommend' => '3.6',
                'safe' => '3',
                'cost' => '2',
                'fun' => '5',
                'tourism' => '4',
                'food' => '3',
                'english' => '5',
                'city' => 'ミシガン州',
                'review' => 'アメリカでのコロナウィルスの感染者はハンパないです。
                    ミシガン州の南西部にあるカラマズーのダウンタウンにある公園のクリスマスライツを見に行きました。
                    ダウンタウンのお店も開いていたので、外から眺めながらぶらぶら。',
                'imgpath' => '650x_11668506.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '32',
                'country_id' => '1',
                'recommend' => '4.1',
                'safe' => '4',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '4',
                'english' => '5',
                'city' => 'ヨセミテ',
                'review' => '妻の幼なじみの友人家族とヨセミテ国立公園に日帰りで行ってきました。
                    私たちは毎年何度もヨセミテに行っていますが、今年では初めての訪問です。',
                'imgpath' => '650x_11664061.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '33',
                'country_id' => '2',
                'recommend' => '4.3',
                'safe' => '5',
                'cost' => '3',
                'fun' => '5',
                'tourism' => '4',
                'food' => '4',
                'english' => '5',
                'city' => 'クリスチナレイク',
                'review' => 'カナダの連休、9月のレイバーデーだったのでキャンプ旅に行ってきました。珍しく弟が同行。。
                    18歳になったので車運転してくれます。。ドライバー付き楽チンキャンプ。2泊3日のキャンプ。',
                'imgpath' => '650x_11644921.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '36',
                'country_id' => '2',
                'recommend' => '3.6',
                'safe' => '3',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '3',
                'food' => '3',
                'english' => '5',
                'city' => 'ウィスラー',
                'review' => '短い夏を精いっぱい楽しみたくて、ウィスラーに3泊しました。
                    1日目 バンクーバーを出発 昼過ぎに到着 アレクサンダー滝とビレッジを散歩
                    2日目 ブラッコム山ハイキング',
                'imgpath' => '650x_11646588.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '31',
                'country_id' => '3',
                'recommend' => '4.0',
                'safe' => '3',
                'cost' => '4',
                'fun' => '3',
                'tourism' => '4',
                'food' => '4',
                'english' => '2',
                'city' => 'メキシコ',
                'review' => 'クリスマス・イブイブ（日本的表現！）のこの日、友人から誘われて本来はトルーカにあるNevado de Tolucaと云う標高4,680mの火山に登山に行ってきました',
                'imgpath' => '650x_11668877.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '30',
                'country_id' => '3',
                'recommend' => '3.5',
                'safe' => '4',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '3',
                'food' => '4',
                'english' => '2',
                'city' => 'カンクン',
                'review' => 'カンクンから一番近い隠れ家リゾート、プエルトモレロス',
                'imgpath' => '650x_11667665.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '4',
                'recommend' => '3.5',
                'safe' => '4',
                'cost' => '4',
                'fun' => '3',
                'tourism' => '3',
                'food' => '4',
                'english' => '3',
                'city' => 'サンパウロ',
                'review' => '比較的自由に街中を歩き回れる「日本」とは大いに異なり、「ブラジル」は外出自粛令発令中、「チリ」や「アルゼンチン」は、ほぼロックダウン状態。
                「ブラジル」は、レストランやら他のお店も再開され、徐々に経済活動が再開されているが、なんせ感染者数も死者も、未だ世界ワースト３位....',
                'imgpath' => '650x_11666359.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '30',
                'country_id' => '4',
                'recommend' => '3.0',
                'safe' => '3',
                'cost' => '2',
                'fun' => '4',
                'tourism' => '2',
                'food' => '3',
                'english' => '2',
                'city' => 'サンパウロ',
                'review' => '2020/4/24現在
                ● 感染者：50,512人
                ● 死 者： 3,365人          
                あれよ、あれよという間に、日本なんぞをぶっちぎって、今や世界ワースト10入りまじかの11位。ロシアと共に競って赤丸急上昇中....。',
                'imgpath' => '650x_11618106.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '33',
                'country_id' => '5',
                'recommend' => '5.2',
                'safe' => '4',
                'cost' => '5',
                'fun' => '5',
                'tourism' => '5',
                'food' => '4',
                'english' => '3',
                'city' => 'バルデス半島',
                'review' => '昨日バルデス半島でほんの少ししか見られなかったペンギンがメインの、プンタ・トンボへのツアーに参加。
                ペンギンがコロニーにいるシーズンの終盤でしたが想像以上のシーンを目にすることができました。',
                'imgpath' => '650x_11608627.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '31',
                'country_id' => '5',
                'recommend' => '3.1',
                'safe' => '3',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '2',
                'city' => 'プエルト',
                'review' => '昨年からハマっているアルゼンチンのLCC、Flybondiでの旅。予約をしたのは、年末年始の一時帰国＋台湾滞在と同時で、昨年の８月でした。',
                'imgpath' => '650x_11608980.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '6',
                'recommend' => '3.5',
                'safe' => '5',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '5',
                'food' => '3',
                'english' => '1',
                'city' => '沖縄',
                'review' => '晴れて日が射している時間に、展望台(登る必要はなく、道路、駐車場からすぐの遊歩道)からが一番水の色がキレイに見えます。食事をするところは混んでいたのでバスで行きました。18時の飛行機に間に合います。',
                'imgpath' => 'src_17664275.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '33',
                'country_id' => '6',
                'recommend' => '3.3',
                'safe' => '5',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '1',
                'city' => '和歌山',
                'review' => '那智熊野神社の拝殿がすばらしく，また大きいので，肝心の後ろの本殿が見ることができない．青岸渡寺側にでて，そこの塀越しが一番よく見える．',
                'imgpath' => '220x220_17617963.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '36',
                'country_id' => '7',
                'recommend' => '3.5',
                'safe' => '4.0',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '3',
                'food' => '5',
                'english' => '2',
                'city' => '弘大',
                'review' => '友人がよく行くソウル弘大グルメ. チャーハンも美味しいです。',
                'imgpath' => '650x_11648798.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '34',
                'country_id' => '7',
                'recommend' => '2.6',
                'safe' => '3',
                'cost' => '3',
                'fun' => '3',
                'tourism' => '2',
                'food' => '4',
                'english' => '1',
                'city' => 'ソウル',
                'review' => '予約購入した映画キャンセルした。
                当日まで待ったけど
                感染者増えすぎ！
                
                あ~~~~も~~~~コロナ!!!',
                'imgpath' => '650x_11640482.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '8',
                'recommend' => '3.1',
                'safe' => '3',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '4',
                'english' => '1',
                'city' => '北京',
                'review' => '中国ってはまる人とはまらない人に分かれる気がする。
                でもある意味環境が日本とだいぶ違うから面白いとは思う。
                個人的に一番面白いと思うのは格差。',
                'imgpath' => '650x_10066255.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '31',
                'country_id' => '8',
                'recommend' => '3.1',
                'safe' => '3',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '3',
                'food' => '4',
                'english' => '2',
                'city' => '上海',
                'review' => '初めて中国を旅行し上海を訪れたら高層ビル群にびっくりすると思う。
                上海自体は観光名称はあってない様なものだけど、周辺に結構良い所がある。',
                'imgpath' => '650x_10916389.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '34',
                'country_id' => '9',
                'recommend' => '3.6',
                'safe' => '4',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '3',
                'city' => 'ウブド',
                'review' => '昨日のウブド、モンキーフォレストの様子です。
                うーん。。。ニュピ（バリ島の新年。静寂の日）みたい。。。',
                'imgpath' => '650x_11667676.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '36',
                'country_id' => '9',
                'recommend' => '3.8',
                'safe' => '3',
                'cost' => '4',
                'fun' => '5',
                'tourism' => '4',
                'food' => '4',
                'english' => '3',
                'city' => 'バリ島',
                'review' => 'バリ島で珍しい、仏教寺院
                シンガラジャから西の方へ行ったところの高台にあり、素晴らしい景色を楽しむ事ができます。',
                'imgpath' => '650x_11666655.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '33',
                'country_id' => '10',
                'recommend' => '3.1',
                'safe' => '3',
                'cost' => '4',
                'fun' => '3',
                'tourism' => '3',
                'food' => '3',
                'english' => '3',
                'city' => 'デリー',
                'review' => 'レートが一日中変動しない日曜日とFXが再開する月曜日にそれぞれ同じ金額をキャシングすることにより突き詰めていきましょう。',
                'imgpath' => '650x_11636493.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '30',
                'country_id' => '10',
                'recommend' => '4.0',
                'safe' => '3',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '5',
                'food' => '4',
                'english' => '4',
                'city' => 'タージマハル',
                'review' => '「なんちゃって世界遺産」が増えちゃって、「世界遺産」自体は今イチ有難みが無くなってしまったが、タージマハルの「世界遺産度」は凄いぞ！
                私的世界遺産Best10に入る・・・他の9個は聞かないでね。',
                'imgpath' => '650x_11624853.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '32',
                'country_id' => '11',
                'recommend' => '3.0',
                'safe' => '3',
                'cost' => '1',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '3',
                'city' => 'リヤド',
                'review' => '２０１９年９月に観光ビザが解禁になったサウジアラビア。世界遺産のマダイン・サレの観光は３月２日まで、ということで、急遽２月に行くことに。',
                'imgpath' => 'src_11608136.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '36',
                'country_id' => '11',
                'recommend' => '4.0',
                'safe' => '5',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '5',
                'english' => '2',
                'city' => 'アル・ウラ',
                'review' => 'マスマク要塞やグランドモスク、スークといった、古いリヤドの風景を残す地域の街歩き。床で食べるサウジ伝統料理も楽しみました。',
                'imgpath' => '650x_11607156.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '32',
                'country_id' => '12',
                'recommend' => '3.3',
                'safe' => '3',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '3',
                'food' => '3',
                'english' => '3',
                'city' => 'カッパドキア',
                'review' => 'まだカッパドキアに行ったことがないりっこちゃんに雰囲気だけでも味わってもらおうと、カッパドキアの端っこにあるウフララ渓谷に行くことにしました。
                カラッと晴れたええ天気でよかったわぁ。',
                'imgpath' => '650x_11657588.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '12',
                'recommend' => '3.5',
                'safe' => '3',
                'cost' => '4',
                'fun' => '3',
                'tourism' => '4',
                'food' => '4',
                'english' => '3',
                'city' => 'ボドルム',
                'review' => '全てのコテージには、緑色の大理石で作られたプライベートプール。広々とした庭園には屋根つきの大きなデイベッドが備えられている。リゾートは東向き。',
                'imgpath' => '650x_11653990.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '34',
                'country_id' => '13',
                'recommend' => '3.5',
                'safe' => '3',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '4',
                'english' => '3',
                'city' => 'パリ',
                'review' => '大都市では近代的なビルを目にすることが多いが
                はじめてフランスの都市に訪れたとき驚いたのは
                まるで中世の世界に訪れたおもうような町並みである。',
                'imgpath' => 'frakouna11.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '33',
                'country_id' => '13',
                'recommend' => '3.8',
                'safe' => '4',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '4',
                'english' => '3',
                'city' => 'パリ',
                'review' => '古い町並みが残っていることから伝統を大切にする気持ちは分かるだろう。
                特にそれを感じたのがパリの歌劇場「オペラガルニエ」である。',
                'imgpath' => 'frakouna41.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '14',
                'recommend' => '3.6',
                'safe' => '4',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '4',
                'city' => 'ヴォルムス',
                'review' => 'ドイツ南西部の町。
                1517年「95ヵ条の論題」で教会に異議を唱えたマルティン・ルターに対して破門と帝国追放刑を決定した帝国議会が開かれた町として知られています。',
                'imgpath' => '650x_11669165.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '32',
                'country_id' => '14',
                'recommend' => '3.1',
                'safe' => '4',
                'cost' => '3',
                'fun' => '3',
                'tourism' => '3',
                'food' => '3',
                'english' => '3',
                'city' => 'ベルリン',
                'review' => '町は第二次世界大戦中に激しい攻撃を受け、大部分が破壊されてしまいました。
                城壁も殆どの部分は大戦後に再建されたもの。',
                'imgpath' => '650x_68526855.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '31',
                'country_id' => '15',
                'recommend' => '3.8',
                'safe' => '3',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '5',
                'english' => '3',
                'city' => 'ナポリ',
                'review' => 'ホテルのそばのトラットリアでスパゲッティーペスカトーレとカンパニアワインでお祝いしました。
                そしてナポリのデザートのストグリアテーラいただき超満足。',
                'imgpath' => '650x_11647281.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '15',
                'recommend' => '3.5',
                'safe' => '3',
                'cost' => '3',
                'fun' => '3',
                'tourism' => '4',
                'food' => '5',
                'english' => '3',
                'city' => 'スパッカナポリ',
                'review' => 'イタリアでも貧富の差、人々は幸せなのでしょうか？',
                'imgpath' => '650x_67375936.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '30',
                'country_id' => '16',
                'recommend' => '4.1',
                'safe' => '4',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '5',
                'food' => '4',
                'english' => '5',
                'city' => 'ロンドン',
                'review' => '偉大なる人類の至宝を数多く所蔵しています。 しかもそれを無料で観られるなんて、とてもありがたいことです。',
                'imgpath' => '650x450_16135506.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '36',
                'country_id' => '16',
                'recommend' => '4.3',
                'safe' => '3',
                'cost' => '5',
                'fun' => '5',
                'tourism' => '5',
                'food' => '3',
                'english' => '5',
                'city' => 'バッキンガム',
                'review' => 'バッキンガム宮殿の中に、絶品の絵を集めた一画があります。フェルメールも一枚、あります。事前申し込みが必要です。
                別館と本館があって、別館は添え物のような感じです。',
                'imgpath' => '650x450_15218878.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '17',
                'recommend' => '3.5',
                'safe' => '4',
                'cost' => '4',
                'fun' => '3',
                'tourism' => '4',
                'food' => '4',
                'english' => '2',
                'city' => 'ノヴォシビルスク',
                'review' => '【五大陸周遊】ノヴォシビルスクで1day トランジット観光！',
                'imgpath' => '650x_11613231.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '31',
                'country_id' => '17',
                'recommend' => '3.6',
                'safe' => '4',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '3',
                'city' => 'モスクワ',
                'review' => 'シベリア鉄道沿線で随一の大都市だけあって、待合室も立派です。',
                'imgpath' => '650x_65655572.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '32',
                'country_id' => '18',
                'recommend' => '3.5',
                'safe' => '3',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '3',
                'city' => 'ケープタウン',
                'review' => '「南アフリカ８日間の旅」を更に素晴らしい思い出にしてくれた笑顔の数々です。一番の良い写真になりました。',
                'imgpath' => '650x_11609364.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '35',
                'country_id' => '18',
                'recommend' => '3.5',
                'safe' => '2',
                'cost' => '4',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '4',
                'city' => 'ステレンボッシュ',
                'review' => '南アフリカのワインの聖地「ステレンボッシュ」は自然豊かな美しい都市です。
                この地方の気候と渓谷がヨーロッパに似ており、現在のケープ・ワインの基礎となったそうです。',
                'imgpath' => '650x_11608609.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '33',
                'country_id' => '19',
                'recommend' => '3.8',
                'safe' => '4',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '5',
                'city' => 'シドニー',
                'review' => 'カンタスのポイントを使ったオーストラリア国内旅行 メルボルンからシドニー',
                'imgpath' => '650x_11667402.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '34',
                'country_id' => '19',
                'recommend' => '3.6',
                'safe' => '3',
                'cost' => '3',
                'fun' => '3',
                'tourism' => '4',
                'food' => '4',
                'english' => '5',
                'city' => 'メルボルン',
                'review' => '朝食をいただきます。コロナの影響で、一品づつ係の人からもらう形式です。
                だから、おかわりしづらいです。',
                'imgpath' => '650x_68425994.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '31',
                'country_id' => '20',
                'recommend' => '4.0',
                'safe' => '4',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '4',
                'english' => '5',
                'city' => 'アオラキ山',
                'review' => 'アオラキ山',
                'imgpath' => '650x_11669199.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'user_id' => '34',
                'country_id' => '20',
                'recommend' => '4.0',
                'safe' => '5',
                'cost' => '3',
                'fun' => '4',
                'tourism' => '4',
                'food' => '3',
                'english' => '5',
                'city' => 'ルートバーンフォールス',
                'review' => 'クイーンズタウンからルートバーン・フォールス・ハットまで日帰りでトレッキングを楽しんできました。原生林の森とエメラルドグリーンのとてもきれいな川の流れと壮大な渓谷を見晴らせるトレッキングです。体力があって時間がある人にはクイーンズタウンからレンタカーで訪れる日帰りトレッキングルートとしてはとてもお勧めです。',
                'imgpath' => '650x_11606889.jpg',
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
        ]);
    }
}
