version: 2.1
jobs:
    build:
        docker:
            - image: circleci/php:7.3-node-browsers
            - image: circleci/mysql:5.7-ram

        environment:
            - APP_DEBUG: true
            - APP_ENV: testing
            - APP_KEY: base64:qN1m0mQJTsI+WBQT5thcPO3U0ZmqqitMlgf0LvZV+m0=
            - DB_CONNECTION: circle_test
            - MYSQL_ALLOW_EMPTY_PASSWORD: true

        working_directory: ~/repo

        steps:
            - checkout 
            - run: sudo apt update
            - run: sudo composer self-update --1
            - run: sudo docker-php-ext-install pdo_mysql
            

            - restore_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
            - run: composer install -n --prefer-dist  
            - save_cache:
                key: composer-v1-{{ checksum "composer.lock" }}
                paths:
                    - vendor

            - restore_cache:
                key: npm-v1-{{ checksum "package-lock.json" }}
            - run: 
                name: npm ci 
                command: |
                    if [ ! -d node_modules ]; then
                        npm ci
                    fi
            - save_cache:
                key: npm-v1-{{ checksum "package-lock.json" }}
                paths:
                    - node_modules

            - run: npm run dev
            - run: php artisan migrate
            - run: 
                name: php test
                command: vendor/bin/phpunit
            